description: 'Rain scenario - multiple small jelly drops falling onto large liquid puddle'
dataset: 'multimaterial_1_scenario_rain'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.0125
  n_particles: 15000
  n_grid: 128
  n_particle_types: 2
  n_frames: 40000
  delta_t: 7.5E-5
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

  MPM_expansion_factor: 1.0
  MPM_n_objects: 6
  MPM_object_type: 'discs'
  MPM_gravity: -10
  MPM_rho_list: [ 1.0, 0.5, 0.25 ]
  MPM_friction: 1.0
  MPM_young_coeff: 1.0

graph_model:
  particle_model_name: 'PDE_MPM'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  input_size: 18
  output_size: 512
  hidden_dim: 512
  n_layers: 4
  aggr_type: 'add'
  embedding_dim: 2

  update_type: 'mlp'
  input_size_update: 520
  n_layers_update: 4
  hidden_dim_update: 128
  output_size_update: 2

  input_size_nnr: 3
  n_layers_nnr: 5
  hidden_dim_nnr: 512
  output_size_nnr: 4
  outermost_linear_nnr: True
  omega: 30.0

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 6
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1

  noise_model_level: 0
  noise_model_level: 1.0E-5

  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: False
  translation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 1E-5
  learning_rate_embedding_start: 1E-2

  MPM_trainer : 'F'
