description: designed by Claude
dataset: multimaterial/multimaterial_1_discs_3types_Claude
simulation:
  params:
    - - 0
      - 0.2
      - 0.4
      - 0.6
      - 0.8
    - - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
  min_radius: 0
  max_radius: 0.0125
  n_particles: 9000
  n_grid: 128
  n_particle_types: 3
  n_frames: 10000
  delta_t: 7.5e-05
  dpos_init: 1.0
  boundary: "no"
  start_frame: 0
  MPM_expansion_factor: 1.0
  MPM_n_objects: 9
  MPM_object_type: discs
  MPM_gravity: -50
  MPM_rho_list:
    - 1.0
    - 0.5
    - 0.25
  MPM_friction: 0.0
  MPM_young_coeff: 1.0
graph_model:
  particle_model_name: PDE_MPM
  mesh_model_name: ""
  prediction: 2nd_derivative
  input_size: 18
  output_size: 512
  hidden_dim: 512
  n_layers: 4
  aggr_type: add
  embedding_dim: 2
  update_type: mlp
  input_size_update: 520
  n_layers_update: 4
  hidden_dim_update: 128
  output_size_update: 2
  inr_type: siren_txy
  input_size_nnr_f: 3
  n_layers_nnr_f: 4
  hidden_dim_nnr_f: 256
  output_size_nnr_f: 1
  outermost_linear_nnr_f: true
  omega_f: 40.0
  omega_f_learning: false
  nnr_f_xy_period: 1.0
plotting:
  colormap: tab10
  arrow_length: 2
  ylim:
    - -0.001
    - 0
training:
  device: "cuda:1"
  n_epochs: 1
  batch_size: 1
  total_steps: 300000
  small_init_batch_size: false
  n_runs: 1
  n_training_frames: 200
  noise_model_level: 1.0e-05
  sparsity: none
  sparsity_freq: 3
  cluster_method: kmeans_auto_embedding
  rotation_augmentation: false
  translation_augmentation: true
  data_augmentation_loop: 100
  fix_cluster_embedding: true
  learning_rate_start: 1E-5
  learning_rate_embedding_start: 1E-2
  learning_rate_NNR_f: 3E-5
claude:
  field_name: F
  ucb_c: 1.414
